### PR TITLE
Fix warning in RN >= 0.58

### LINKED ISSUE #2620: YellowBox warning on react-native 0.58.0-rc.1
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.58.0-rc.1
react: 16.6.3
react-native-maps: from git, currently at commit ccd48792b74ba810b0e01c60dfc2b5c42f191e72

Target Platform: iOS (GoogleMaps)

### Steps to Reproduce

I think just launch application with embedded MapView is enough to reproduce.

### Expected Behavior

No warnings.

### Actual Behavior

Yellow box warning popups: Accessing view manager configs directly off UIManager view UIManager[‘AIRGoogleMap’] is no longer supported.

According to stack trace, warning is here: decorateMapComponent.js:35
```
export const googleMapIsInstalled = !!NativeModules.UIManager[getAirMapName(PROVIDER_GOOGLE)];
```

warning in maps

### PR DESCRIPTION
**Pull request by vovkasm**
fixes #2620 YellowBox warning on react-native 0.58.0-rc.1

### Does any other open PR do the same thing?

No

### What issue is this PR fixing?

#2620

### How did you test this PR?

1. Update ios application that use react-native-maps to react-native 0.58.0-rc.3
2. Open screen with any map component
3. Check that no warning after this PR applied

### CODE REVIEW

**Comment by rborn** [comment]
@christopherdro @alvelig LGTM 🐽

File: lib/components/decorateMapComponent.js [hunk 1]
```diff
@@ -32,7 +32,17 @@ export const createNotSupportedComponent = message => () => {
   return null;
 };
 
-export const googleMapIsInstalled = !!NativeModules.UIManager[getAirMapName(PROVIDER_GOOGLE)];
+function getViewManagerConfig(viewManagerName) {
+  const UIManager = NativeModules.UIManager;
+  if (!UIManager.getViewManagerConfig) {
```
Comment (alvelig) [inline lib/components/decorateMapComponent.js]: We have lodash in dependencies, so I think testing for a function is more accurate. And I'd put it the way around:
```
_.isFunction(UIManager.getViewManagerConfig) { // RN >= 0.58
  return UIManager.getViewManagerConfig(viewManagerName);
}
return return UIManager[viewManagerName]; // RN < 0.58

Comment (alvelig) [reply lib/components/decorateMapComponent.js]: Ok, seems reasonable

**Comment by alvelig** [comment]
LGTM

**Comment by St1maSphere** [comment]
@alvelig Could you prompt, where could this request be merged? 
Seems critical for me

**Comment by declanelcocks** [comment]
Added a follow up PR https://github.com/react-native-community/react-native-maps/pull/2740

**Comment by andrew-magicfitness** [comment]
i need this pr merged
